root = "."
tmp_dir = "tmp"

[build]
bin = "main" 
cmd = "go build -o ./tmp/main ./cmd/api/main.go" 
delay = 1000 # ms
exclude_dir = ["tmp", "_docs", "_req"] 
exclude_file = [] 
full_bin = "./tmp/main" 
include_dir = [] 
include_ext = ["go"] 
kill_delay = 500 # ms
log = "air.log" 
send_interrupt = false 
stop_on_error = true 

[log]
time = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
