name: "ide-app"

services:
  ide-app:
    container_name: ide-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - ide-network
    working_dir: /app
    volumes:
      - .:/app

networks:
  ide-network:
    driver: bridge
